### PR TITLE
echo server example

### PR DESCRIPTION
**Pull request by TudorHulban**
echo server example.

### CODE REVIEW

**Comment by savsgio** [comment]
Please, simplify the example:

```go
package main

import (
	"github.com/savsgio/atreugo/v11"
)

func main() {
	config := atreugo.Config{
		Addr: "0.0.0.0:8000",
	}
	server := atreugo.New(config)

	server.GET("/e/{echo}", func(ctx *atreugo.RequestCtx) error {
		msg := ctx.UserValue("echo")
	        return ctx.TextResponse(fmt.Sprintf("Message: %s", msg))
	})

	if err := server.ListenAndServe(); err != nil {
		panic(err)
	}
}
```

**Comment by savsgio** [comment]
Sorry, but your example it's too complex for a basic echo example.

**Comment by TudorHulban** [comment]
If you are not fine with contributors code why do ask for PR? Do not expect somebody else to write code exactly like you do.

**Comment by savsgio** [comment]
You can write your code as you want, but in my repositories i decide which type, format and complexity are in them. I don't trying to offend you with my suggestion, so if you couldn't understand it, i'm sorry.

Thanks

**Comment by savsgio** [comment]
I like the simple and basic examples which developers could understand quickly, for that my suggestion

**Pull request closed without merging**
